"""Generate the human-readable validation report and the gap analysis."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

MAPPINGS_DIR = Path(__file__).parent / "mappings"

DISCLAIMER = (
    "> **Scope note:** This report was generated by providence from the eval "
    "artifacts referenced in the manifest. The framework mapping is an "
    "interpretation intended to structure evidence, not legal or regulatory "
    "advice, and does not by itself constitute independent validation. "
    "Requirements marked *NOT EVIDENCED* must be addressed outside this tool."
)


def load_mapping(name: str) -> dict[str, Any]:
    path = MAPPINGS_DIR / f"{name}.yaml"
    if not path.exists():
        available = sorted(p.stem for p in MAPPINGS_DIR.glob("*.yaml"))
        raise FileNotFoundError(f"Unknown mapping '{name}'. Available: {available}")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def present_artifacts(results: dict[str, Any], has_drift: bool) -> set[str]:
    """Which evidence artifact kinds exist in this pack?"""
    kinds = {"model_card", "manifest", "suite_results", "dataset_hashes"}
    model = results["model"]
    if model.get("tier_rationale"):
        kinds.add("tier_rationale")
    if model.get("limitations"):
        kinds.add("limitations")
    if has_drift:
        kinds.add("drift_comparison")
    return kinds


def gap_analysis(results: dict[str, Any], mapping: dict[str, Any], has_drift: bool) -> list[dict[str, Any]]:
    """Map pack artifacts to requirements — outcome-aware.

    Artifact *presence* is necessary but not sufficient: a requirement
    leaning on suite results is not 'EVIDENCED' when the suites mapped to
    it are failing. Those rows get an explicit FAILING status, because an
    evidence table that reads green while the tests are red is worse than
    no table.
    """
    available = present_artifacts(results, has_drift)
    suites = results["suites"]
    rows = []
    for req in mapping["requirements"]:
        sources = list(req.get("satisfied_by", []))
        usable = [s for s in sources if s != "manual" and s in available]
        needs_manual = "manual" in sources
        if usable and not needs_manual:
            status = "EVIDENCED"
        elif usable and needs_manual:
            status = "PARTIAL (manual input required)"
        else:
            status = "NOT EVIDENCED"

        failing_suites: list[str] = []
        if "suite_results" in usable:
            mapped = [s for s in suites if req["id"] in (s.get("requirement_ids") or [])]
            relevant = mapped if mapped else suites
            failing_suites = [s["suite"] for s in relevant if s["verdict"].startswith("FAIL")]
            if failing_suites:
                status = f"FAILING ({len(failing_suites)}/{len(relevant)} suites below threshold)"
        rows.append(
            {
                "id": req["id"],
                "title": req["title"],
                "status": status,
                "evidence": usable,
                "failing_suites": failing_suites,
            }
        )
    return rows


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def _cell(text: Any) -> str:
    """Collapse whitespace so multiline YAML strings don't break table rows."""
    return " ".join(str(text).split())


def _render_judge_evidence(add, je: dict[str, Any]) -> None:
    """Judge-disagreement evidence for one suite. The judges are part of
    the measurement instrument, so their reliability is reported alongside
    what they measured — including, loudly, when the headline verdict
    depends on which judge you believe."""
    panel = ", ".join(
        f"`{j['name']}` ({j['type']}{'/' + j['model_id'] if j['model_id'] else ''})"
        for j in je["judges"]
    )
    add(f"- Judge panel ({je['n_judges']}): {panel}; decision rule: **{je['decision']}**")
    add(f"- Rubric: {_cell(je['rubric'])}")
    if je["n_judges"] == 1:
        add(
            "- **Single judge — no disagreement evidence.** This suite's scores "
            "rest entirely on one judge being right; agreement statistics "
            "require a panel of at least two."
        )
    else:
        agr = je["agreement"]
        if "settledness" in agr:
            sv = agr["settledness"]
            add(
                f"- Panel agreement: {_pct(agr['rate'])} of items "
                f"({agr['n_agreed']}/{je['n_items']}), 95% CI "
                f"[{_pct(sv['ci95_low'])}, {_pct(sv['ci95_high'])}] vs required "
                f"{_pct(agr['min_agreement'])} — agreement verdict **{sv['verdict']}**"
            )
        else:
            add(
                f"- Panel agreement: {_pct(agr['rate'])} of items "
                f"({agr['n_agreed']}/{je['n_items']}), 95% CI "
                f"[{_pct(agr['ci95_low'])}, {_pct(agr['ci95_high'])}]"
            )
        for pw in je["pairwise"]:
            if pw["kappa"] is not None:
                add(
                    f"- `{pw['judge_a']}` vs `{pw['judge_b']}`: raw agreement "
                    f"{_pct(pw['observed_agreement'])}, chance-corrected κ = {pw['kappa']:.2f} "
                    f"(over {pw['n_pairs']} items where both verdicts were valid)"
                )
            elif pw["observed_agreement"] is not None:
                add(
                    f"- `{pw['judge_a']}` vs `{pw['judge_b']}`: raw agreement "
                    f"{_pct(pw['observed_agreement'])}; κ undefined (no variation "
                    "to correct for chance — the raw rate is the honest number)"
                )
            else:
                add(
                    f"- `{pw['judge_a']}` vs `{pw['judge_b']}`: no items where "
                    "both verdicts were valid"
                )
        rates = ", ".join(
            f"`{p['name']}` {_pct(p['pass_rate'])} ({p['verdict']})" for p in je["per_judge"]
        )
        if je["judge_dependent"]:
            add(
                f"- **JUDGE-DEPENDENT:** the pass rate's side of the threshold flips "
                f"with the choice of judge — {rates}. Treat the suite verdict as "
                "unsettled judge evidence, not a property of the model."
            )
        else:
            add(f"- Judge sensitivity: verdict direction stable across judges ({rates})")
    if je["n_invalid_responses"] > 0:
        per = ", ".join(
            f"`{name}`: {count}" for name, count in je["invalid_by_judge"].items() if count
        )
        add(
            f"- **{je['n_invalid_responses']} unparseable judge response(s)** recorded as "
            f"`invalid` and counted against agreement and item passes ({per}) — "
            "never silently coerced to a verdict"
        )


def render_markdown(
    results: dict[str, Any],
    mappings: list[str],
    manifest: dict[str, Any] | None = None,
    drift: dict[str, Any] | None = None,
) -> str:
    model = results["model"]
    lines: list[str] = []
    add = lines.append

    add(f"# Model Validation Evidence Report — {model['name']} v{model['version']}")
    add("")
    add(DISCLAIMER)
    add("")

    add("## 1. Model card")
    add("")
    add(f"| Field | Value |")
    add(f"|---|---|")
    add(f"| Model | {model['name']} |")
    add(f"| Version | {model['version']} |")
    add(f"| Vendor | {model['vendor']} |")
    add(f"| Use case | {_cell(model['use_case'])} |")
    add(f"| Owner | {_cell(model['owner'])} |")
    add(f"| Materiality tier | {model['materiality_tier']} |")
    add(f"| Provider under test | {results['provider'].get('type')} / {results['provider'].get('model_id', '')} |")
    add("")
    add(f"**Tier rationale.** {_cell(model['tier_rationale'])}")
    add("")
    if model.get("description"):
        add(f"**Description.** {_cell(model['description'])}")
        add("")
    if model.get("limitations"):
        add("**Known limitations and conditions of use.**")
        add("")
        for lim in model["limitations"]:
            add(f"- {lim}")
        add("")

    add("## 2. Outcomes analysis")
    add("")
    stats_cfg = results.get("statistics") or {}
    if stats_cfg.get("intervals") == "clopper_pearson":
        add("Pass rates carry Clopper-Pearson exact 95% confidence intervals")
        add("(**strict mode**: coverage is guaranteed to be at least 95% at every")
        add("sample size and true rate, at the price of systematically wider")
        add("intervals than the default Wilson score). A suite is marked")
    else:
        add("Pass rates carry Wilson 95% confidence intervals. A suite is marked")
    add("**PASS** only when the *lower* confidence bound clears its acceptance")
    add("threshold; **PASS (point)** means the point estimate clears it but the")
    add("sample is too small to call the evidence settled. Unsettled verdicts")
    add("carry a sample-size certificate: how many items it would take to")
    add("settle them, by exact binomial power at the observed rate. Suites")
    add("whose items declare a `cluster` (a shared source document or template)")
    add("use cluster-adjusted intervals, so correlated items are not counted")
    add("as independent evidence. Suites scored by LLM judges carry their own")
    add("judge-disagreement evidence in the suite detail below — a judge's")
    add("verdict is a measurement, not ground truth.")
    add("")
    add("| Suite | Metric | Items | Pass rate | 95% CI | Threshold | Verdict |")
    add("|---|---|---|---|---|---|---|")
    for s in results["suites"]:
        add(
            f"| {s['suite']} | {s['metric']} | {s['n_items']} "
            f"| {_pct(s['pass_rate'])} | [{_pct(s['ci95_low'])}, {_pct(s['ci95_high'])}] "
            f"| {_pct(s['threshold'])} | **{s['verdict']}** |"
        )
    add("")

    for s in results["suites"]:
        failures = [it for it in s["items"] if not it["passed"]]
        add(f"### Suite: {s['suite']}")
        add("")
        if s.get("description"):
            add(s["description"])
            add("")
        add(f"- Dataset: `{s['dataset']}` (sha256 `{s['dataset_sha256'][:16]}…`)")
        add(f"- Runs per item: {s['runs_per_item']} (an item passes only if every run passes)")
        if s.get("requirement_ids"):
            add(f"- Mapped requirements: {', '.join(s['requirement_ids'])}")
        if s.get("ci_method") == "wilson_cluster_adjusted":
            add(
                f"- Clustered items: {s['n_clusters']} clusters, design effect "
                f"{s['deff']:.2f}, effective sample size {s['n_eff']:.1f} — "
                "the interval and verdict use the effective sample size"
            )
            if s.get("strict_interval_overridden_by_clustering"):
                add(
                    "- Strict (Clopper-Pearson) intervals were configured, but the "
                    "guarantee holds only for independent items: this clustered "
                    "suite uses the cluster-adjusted interval instead — a strict "
                    "label on correlated data would be a false promise"
                )
        je = s.get("judge_evidence")
        if je is not None:
            _render_judge_evidence(add, je)
        add(f"- Result: {s['n_passed']}/{s['n_items']} items passed — verdict **{s['verdict']}**")
        cert = s.get("sample_size_certificate")
        if cert is not None:
            approx = " (approximate: clustered items)" if cert.get("approximate_under_clustering") else ""
            if cert["status"] == "ok":
                add(
                    f"- Sample-size certificate: at the observed rate "
                    f"({_pct(cert['planning_rate'])}), ≈{cert['n_required']} total items "
                    f"({cert['additional_items']} more) would settle **{cert['target_verdict']}** "
                    f"with {cert['requested_power']:.0%} probability{approx}"
                )
            elif cert["status"] == "unreachable":
                add(
                    "- Sample-size certificate: the observed rate is too close to the "
                    "threshold for more items to settle this verdict — treat the "
                    f"threshold itself as the open question{approx}"
                )
        add("")
        if failures:
            add(f"<details><summary>{len(failures)} failing item(s)</summary>")
            add("")
            for it in failures:
                last = it["runs"][-1]
                add(f"- `{it['id']}`: {last['detail']}")
            add("")
            add("</details>")
            add("")

    if drift is not None:
        add("## 3. Ongoing monitoring — drift vs. prior run")
        add("")
        add(f"Compared against prior evidence pack `{drift['baseline_pack']}`.")
        add("")
        n_comparable = sum(1 for r in drift["suites"] if r.get("comparable"))
        if str(drift.get("method", "")).startswith("fisher_midp"):
            add("p-values are two-sided **mid-p** Fisher tests: tables exactly as")
            add("probable as the observed one get half weight, recovering the power")
            add("plain Fisher sacrifices to discreteness at small n. The honest")
            add("trade: mid-p's false-alarm rate is approximately the nominal level")
            add("on average but is not guaranteed never to exceed it. Holm")
            add(f"adjustment applies across the {n_comparable} comparable")
        else:
            add("p-values are two-sided Fisher's exact tests (exact at any sample")
            add(f"size) with Holm adjustment across the {n_comparable} comparable")
        add("suite(s), so monitoring several suites at once does not inflate the")
        add("false-drift rate. Suites whose dataset, metric, or runs-per-item")
        add("changed are **not comparable** and get no p-value at all — a test")
        add("across different datasets would be a number, not evidence.")
        add("")
        add("| Suite | Prior rate | Current rate | p (exact) | p (Holm) | Drift at α=0.05 |")
        add("|---|---|---|---|---|---|")
        for row in drift["suites"]:
            if row.get("comparable"):
                add(
                    f"| {row['suite']} | {_pct(row['rate_a'])} | {_pct(row['rate_b'])} "
                    f"| {row['p_value']:.4f} | {row['p_holm']:.4f} "
                    f"| {'**YES**' if row['significant'] else 'no'} |"
                )
            else:
                add(
                    f"| {row['suite']} | {_pct(row['rate_a'])} | {_pct(row['rate_b'])} "
                    f"| — | — | **NOT COMPARABLE** ({row['reason']}) |"
                )
        add("")

    # Monitoring evidence only counts if at least one suite was actually
    # comparable — a drift section full of NOT COMPARABLE rows evidences
    # nothing.
    drift_evidenced = drift is not None and any(r.get("comparable") for r in drift["suites"])
    section = 4 if drift is not None else 3
    for mapping_name in mappings:
        mapping = load_mapping(mapping_name)
        rows = gap_analysis(results, mapping, has_drift=drift_evidenced)
        add(f"## {section}. Requirement coverage — {mapping['framework']}")
        add("")
        add("| Requirement | Title | Status | Evidence in this pack |")
        add("|---|---|---|---|")
        for r in rows:
            ev = ", ".join(r["evidence"]) if r["evidence"] else "—"
            if r.get("failing_suites"):
                ev += f" (failing: {', '.join(r['failing_suites'])})"
            add(f"| {r['id']} | {r['title']} | {r['status']} | {ev} |")
        add("")
        gaps = [r for r in rows if r["status"] != "EVIDENCED"]
        if gaps:
            add(f"**Open items ({len(gaps)}):** " + ", ".join(g["id"] for g in gaps) + ".")
            add("")
        section += 1

    add(f"## {section}. Reproducibility")
    add("")
    add("Integrity: the manifest pins the SHA-256 of the configuration, every")
    add("dataset, and every generated artifact. Run `providence verify <pack-dir>`")
    add("to confirm the pack matches what was produced (hash-pinning detects")
    add("modification; it is not a signature). Re-running `providence run` against")
    add("the same config and datasets reproduces the run only to the extent the")
    add("underlying provider is deterministic.")
    add("")
    if manifest is not None:
        add(f"- Pack ID: `{manifest['pack_id']}`")
        add(f"- Config sha256: `{manifest['config_sha256']}`")
        add(f"- Created (UTC): {manifest['created_utc']}")
        add(f"- providence version: {manifest['providence_version']}")
        add("")

    return "\n".join(lines)
